theme: jekyll-theme-minimal
title: Camila Castillo-Vilcahuaman
author: GitHub User
email: castillo.vilcahuaman
description: A wonderful site
twitter_username: reymonera
github_username:  reymonera
url: 
base_url: 

# Build settings
markdown: kramdown
# remote_theme: chrisbobbe/jekyll-theme-prologue
